name: Test acceptance test deploy

on: [push]

env:
  APP: dp-regel-sats

jobs:
  acceptance-tests:
    name: Run acceptance tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: navikt/dagpenger-funksjonelle-tester
      - uses: nais/deploy/actions/deploy@v1
        name: Run tests
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          VAR: GITHUB_REPO=${{ env.APP }}
          RESOURCE: nais/tests.yml
        timeout-minutes: 5
